evaluate summary-llm-judge vs human-judge
recoverycompanion/reco pull request #32
Opened 2024-07-25 06:42 UTC by mike-khor

Analysis can be found in `reco_analysis/notebooks/judge/2.0_eval_llm_judge_summarization.ipynb`

2024-07-30 06:03 UTC, garyukong requested changes
I’m getting a bit confused regarding the versioning of the different evaluations (e.g., what transcripts/summaries they’re evaluating). It seems like these are the naming conventions currently being used:

	•	data/evaluations/summaries_1.0_evaluation_2.1.csv
	•	data/evaluations/summaries_1.0_evaluation_2.2_split.csv
	•	data/evaluations/summaries_1.0_evaluation_2.2.csv
	•	data/evaluations/summaries_1.0_evaluation_2.csv
	•	data/evaluations/summaries_1.0_evaluation.csv
	•	data/evaluations/transcripts_1.0_evaluation_2.1.csv
	•	data/evaluations/transcripts_1.0_evaluation_2.csv

I thought we agreed on a consistent naming convention in our earlier discussions. In my current PR, I’ve included a module called path_maker.py to handle paths and clearly specify whether something is an evaluation of a summary, a summary, an evaluation of a transcript, or a transcript. I think it would be beneficial to approve and merge my PR first, then implement this module here for consistency.

Also, have we refined the LLM as a judge for transcripts? Recall the issue where the LLM judge would assign a score of ‘1’ if the chatbot asked about a symptom/vital/medicine, regardless of whether the patient responded. If we’ve updated the LLM judge prompt, then the CSV evaluations I conducted in 2307 are now outdated and need to be rerun with the new LLM judge.

2024-07-30 06:03 UTC, garyukong commented on reco_analysis/notebooks/experiment_analysis/01_analyze_gpts.ipynb
The evals need to be reran if you're using a new LLM judge prompts (remember the old ones didn't work correctly because they were simply asking whether or not a symptom was asked or not, instead of checking whether they).

Recall evals done at 2307 were prior to you updating the LLMs.
    "GPT-3.5": 'transcripts_eval_short_gpt3.5_basepat_basedoc_2307.csv',
    "GPT-4o": 'transcripts_eval_short_gpt4o_basepat_basedoc_2307.csv',
    "GPT-4o-mini": 'transcripts_eval_short_gpt4o-m_basepat_basedoc_2307.csv',

2024-07-31 03:54 UTC, mike-khor commented
> what transcripts/summaries they’re evaluating

Every notebook and its corresponding csv file is based on the basedoc and base summary prompt, the very first one. The iterations here are on _Summary-LLM-judge prompts_ only, and hence doesn't fit the naming convention you suggested.

> Also, have we refined the LLM as a judge for transcripts? 

Not in this PR. That is next on my TODO, in a separate PR

2024-07-31 03:55 UTC, mike-khor commented on reco_analysis/notebooks/experiment_analysis/01_analyze_gpts.ipynb
yup agreed. will run with improved transcript-LLM-judge in a separate PR

2024-08-01 16:53 UTC, garyukong approved these changes

2024-08-02 04:08 UTC, merged